cache:
  paths:
    - node_modules/
stages:
  - build
  - deploy
  
build:
  image: node:14
  stage: build
  script:
    - npm install
    - CI=false npm run build
    - apk-get update && apk-get install -y tar 
    - tar -cvzf build.tar.gz build
  artifacts:
    paths:
      - build.tar.gz
  only:
    - staging

deploy:
  image: alpine
  stage: deploy
  only:
    - staging
  script: 
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan <EC2_HOST_URL> >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - scp -o stricthostkeychecking=no -r build.tar.gz ubuntu@<EC2_HOST_URL>:/var/www/html/frontend
    - ssh -o StrictHostKeyChecking=no ubuntu@<EC2_HOST_URL> "sudo -S chmod 777 /var/www/html/frontend; cd /var/www/html/frontend; ls -ltra; tar -zxvf build.tar.gz; mv build build_new"
